ENVIRONMENT: development
LOG_LEVEL: info
PORT: 8080
MON_PORT: 8888
GRPC_PORT: 8086
JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
DIMO_REGISTRY_CHAIN_ID: 80002
VEHICLE_NFT_CONTRACT_ADDRESS: 0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8 