// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: pkg/grpc/credit-tracker.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata keys for error details
type MetadataKey int32

const (
	MetadataKey_METADATA_KEY_UNSPECIFIED       MetadataKey = 0
	MetadataKey_METADATA_KEY_ASSET_DID         MetadataKey = 1
	MetadataKey_METADATA_KEY_TRANSACTION_HASH  MetadataKey = 2
	MetadataKey_METADATA_KEY_DEVELOPER_LICENSE MetadataKey = 3
)

// Enum value maps for MetadataKey.
var (
	MetadataKey_name = map[int32]string{
		0: "METADATA_KEY_UNSPECIFIED",
		1: "METADATA_KEY_ASSET_DID",
		2: "METADATA_KEY_TRANSACTION_HASH",
		3: "METADATA_KEY_DEVELOPER_LICENSE",
	}
	MetadataKey_value = map[string]int32{
		"METADATA_KEY_UNSPECIFIED":       0,
		"METADATA_KEY_ASSET_DID":         1,
		"METADATA_KEY_TRANSACTION_HASH":  2,
		"METADATA_KEY_DEVELOPER_LICENSE": 3,
	}
)

func (x MetadataKey) Enum() *MetadataKey {
	p := new(MetadataKey)
	*p = x
	return p
}

func (x MetadataKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataKey) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_credit_tracker_proto_enumTypes[0].Descriptor()
}

func (MetadataKey) Type() protoreflect.EnumType {
	return &file_pkg_grpc_credit_tracker_proto_enumTypes[0]
}

func (x MetadataKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataKey.Descriptor instead.
func (MetadataKey) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{0}
}

// ErrorReason represents the specific reason for a credit tracker error
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED               ErrorReason = 0
	ErrorReason_ERROR_REASON_INSUFFICIENT_CREDITS      ErrorReason = 1
	ErrorReason_ERROR_REASON_INVALID_ASSET_DID         ErrorReason = 2
	ErrorReason_ERROR_REASON_INVALID_DEVELOPER_LICENSE ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "ERROR_REASON_INSUFFICIENT_CREDITS",
		2: "ERROR_REASON_INVALID_ASSET_DID",
		3: "ERROR_REASON_INVALID_DEVELOPER_LICENSE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":               0,
		"ERROR_REASON_INSUFFICIENT_CREDITS":      1,
		"ERROR_REASON_INVALID_ASSET_DID":         2,
		"ERROR_REASON_INVALID_DEVELOPER_LICENSE": 3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_credit_tracker_proto_enumTypes[1].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_pkg_grpc_credit_tracker_proto_enumTypes[1]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{1}
}

// ErrorDomain represents the domain where the error occurred
type ErrorDomain int32

const (
	ErrorDomain_ERROR_DOMAIN_UNSPECIFIED    ErrorDomain = 0
	ErrorDomain_ERROR_DOMAIN_CREDIT_TRACKER ErrorDomain = 1
)

// Enum value maps for ErrorDomain.
var (
	ErrorDomain_name = map[int32]string{
		0: "ERROR_DOMAIN_UNSPECIFIED",
		1: "ERROR_DOMAIN_CREDIT_TRACKER",
	}
	ErrorDomain_value = map[string]int32{
		"ERROR_DOMAIN_UNSPECIFIED":    0,
		"ERROR_DOMAIN_CREDIT_TRACKER": 1,
	}
)

func (x ErrorDomain) Enum() *ErrorDomain {
	p := new(ErrorDomain)
	*p = x
	return p
}

func (x ErrorDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_credit_tracker_proto_enumTypes[2].Descriptor()
}

func (ErrorDomain) Type() protoreflect.EnumType {
	return &file_pkg_grpc_credit_tracker_proto_enumTypes[2]
}

func (x ErrorDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorDomain.Descriptor instead.
func (ErrorDomain) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{2}
}

// Request message for checking credits
type CreditCheckRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeveloperLicense string                 `protobuf:"bytes,1,opt,name=developer_license,json=developerLicense,proto3" json:"developer_license,omitempty"`
	AssetDid         string                 `protobuf:"bytes,2,opt,name=asset_did,json=assetDid,proto3" json:"asset_did,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreditCheckRequest) Reset() {
	*x = CreditCheckRequest{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCheckRequest) ProtoMessage() {}

func (x *CreditCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCheckRequest.ProtoReflect.Descriptor instead.
func (*CreditCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *CreditCheckRequest) GetDeveloperLicense() string {
	if x != nil {
		return x.DeveloperLicense
	}
	return ""
}

func (x *CreditCheckRequest) GetAssetDid() string {
	if x != nil {
		return x.AssetDid
	}
	return ""
}

// Response message for credit check
type CreditCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemainingCredits int64                  `protobuf:"varint,1,opt,name=remaining_credits,json=remainingCredits,proto3" json:"remaining_credits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreditCheckResponse) Reset() {
	*x = CreditCheckResponse{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCheckResponse) ProtoMessage() {}

func (x *CreditCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCheckResponse.ProtoReflect.Descriptor instead.
func (*CreditCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *CreditCheckResponse) GetRemainingCredits() int64 {
	if x != nil {
		return x.RemainingCredits
	}
	return 0
}

// Request message for deducting credits
type CreditDeductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeveloperLicense string                 `protobuf:"bytes,1,opt,name=developer_license,json=developerLicense,proto3" json:"developer_license,omitempty"`
	AssetDid         string                 `protobuf:"bytes,2,opt,name=asset_did,json=assetDid,proto3" json:"asset_did,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreditDeductRequest) Reset() {
	*x = CreditDeductRequest{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditDeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditDeductRequest) ProtoMessage() {}

func (x *CreditDeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditDeductRequest.ProtoReflect.Descriptor instead.
func (*CreditDeductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *CreditDeductRequest) GetDeveloperLicense() string {
	if x != nil {
		return x.DeveloperLicense
	}
	return ""
}

func (x *CreditDeductRequest) GetAssetDid() string {
	if x != nil {
		return x.AssetDid
	}
	return ""
}

func (x *CreditDeductRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response message for credit deduction
type CreditDeductResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemainingCredits int64                  `protobuf:"varint,1,opt,name=remaining_credits,json=remainingCredits,proto3" json:"remaining_credits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreditDeductResponse) Reset() {
	*x = CreditDeductResponse{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditDeductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditDeductResponse) ProtoMessage() {}

func (x *CreditDeductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditDeductResponse.ProtoReflect.Descriptor instead.
func (*CreditDeductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *CreditDeductResponse) GetRemainingCredits() int64 {
	if x != nil {
		return x.RemainingCredits
	}
	return 0
}

// Request message for refunding credits
type RefundCreditsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeveloperLicense string                 `protobuf:"bytes,1,opt,name=developer_license,json=developerLicense,proto3" json:"developer_license,omitempty"`
	AssetDid         string                 `protobuf:"bytes,2,opt,name=asset_did,json=assetDid,proto3" json:"asset_did,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional reason for refunding credits (e.g., "cancelled_operation", "error_recovery")
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundCreditsRequest) Reset() {
	*x = RefundCreditsRequest{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundCreditsRequest) ProtoMessage() {}

func (x *RefundCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundCreditsRequest.ProtoReflect.Descriptor instead.
func (*RefundCreditsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *RefundCreditsRequest) GetDeveloperLicense() string {
	if x != nil {
		return x.DeveloperLicense
	}
	return ""
}

func (x *RefundCreditsRequest) GetAssetDid() string {
	if x != nil {
		return x.AssetDid
	}
	return ""
}

func (x *RefundCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response message for credit refund
type RefundCreditsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemainingCredits int64                  `protobuf:"varint,1,opt,name=remaining_credits,json=remainingCredits,proto3" json:"remaining_credits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefundCreditsResponse) Reset() {
	*x = RefundCreditsResponse{}
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundCreditsResponse) ProtoMessage() {}

func (x *RefundCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_credit_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundCreditsResponse.ProtoReflect.Descriptor instead.
func (*RefundCreditsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_credit_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *RefundCreditsResponse) GetRemainingCredits() int64 {
	if x != nil {
		return x.RemainingCredits
	}
	return 0
}

var File_pkg_grpc_credit_tracker_proto protoreflect.FileDescriptor

const file_pkg_grpc_credit_tracker_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/grpc/credit-tracker.proto\x12\x04grpc\"^\n" +
	"\x12CreditCheckRequest\x12+\n" +
	"\x11developer_license\x18\x01 \x01(\tR\x10developerLicense\x12\x1b\n" +
	"\tasset_did\x18\x02 \x01(\tR\bassetDid\"B\n" +
	"\x13CreditCheckResponse\x12+\n" +
	"\x11remaining_credits\x18\x01 \x01(\x03R\x10remainingCredits\"w\n" +
	"\x13CreditDeductRequest\x12+\n" +
	"\x11developer_license\x18\x01 \x01(\tR\x10developerLicense\x12\x1b\n" +
	"\tasset_did\x18\x02 \x01(\tR\bassetDid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"C\n" +
	"\x14CreditDeductResponse\x12+\n" +
	"\x11remaining_credits\x18\x01 \x01(\x03R\x10remainingCredits\"\x90\x01\n" +
	"\x14RefundCreditsRequest\x12+\n" +
	"\x11developer_license\x18\x01 \x01(\tR\x10developerLicense\x12\x1b\n" +
	"\tasset_did\x18\x02 \x01(\tR\bassetDid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"D\n" +
	"\x15RefundCreditsResponse\x12+\n" +
	"\x11remaining_credits\x18\x01 \x01(\x03R\x10remainingCredits*\x8e\x01\n" +
	"\vMetadataKey\x12\x1c\n" +
	"\x18METADATA_KEY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16METADATA_KEY_ASSET_DID\x10\x01\x12!\n" +
	"\x1dMETADATA_KEY_TRANSACTION_HASH\x10\x02\x12\"\n" +
	"\x1eMETADATA_KEY_DEVELOPER_LICENSE\x10\x03*\xa2\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!ERROR_REASON_INSUFFICIENT_CREDITS\x10\x01\x12\"\n" +
	"\x1eERROR_REASON_INVALID_ASSET_DID\x10\x02\x12*\n" +
	"&ERROR_REASON_INVALID_DEVELOPER_LICENSE\x10\x03*L\n" +
	"\vErrorDomain\x12\x1c\n" +
	"\x18ERROR_DOMAIN_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_DOMAIN_CREDIT_TRACKER\x10\x012\xec\x01\n" +
	"\rCreditTracker\x12E\n" +
	"\fCheckCredits\x12\x18.grpc.CreditCheckRequest\x1a\x19.grpc.CreditCheckResponse\"\x00\x12H\n" +
	"\rDeductCredits\x12\x19.grpc.CreditDeductRequest\x1a\x1a.grpc.CreditDeductResponse\"\x00\x12J\n" +
	"\rRefundCredits\x12\x1a.grpc.RefundCreditsRequest\x1a\x1b.grpc.RefundCreditsResponse\"\x00B1Z/github.com/DIMO-Network/credit-tracker/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_credit_tracker_proto_rawDescOnce sync.Once
	file_pkg_grpc_credit_tracker_proto_rawDescData []byte
)

func file_pkg_grpc_credit_tracker_proto_rawDescGZIP() []byte {
	file_pkg_grpc_credit_tracker_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_credit_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_credit_tracker_proto_rawDesc), len(file_pkg_grpc_credit_tracker_proto_rawDesc)))
	})
	return file_pkg_grpc_credit_tracker_proto_rawDescData
}

var file_pkg_grpc_credit_tracker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_grpc_credit_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_grpc_credit_tracker_proto_goTypes = []any{
	(MetadataKey)(0),              // 0: grpc.MetadataKey
	(ErrorReason)(0),              // 1: grpc.ErrorReason
	(ErrorDomain)(0),              // 2: grpc.ErrorDomain
	(*CreditCheckRequest)(nil),    // 3: grpc.CreditCheckRequest
	(*CreditCheckResponse)(nil),   // 4: grpc.CreditCheckResponse
	(*CreditDeductRequest)(nil),   // 5: grpc.CreditDeductRequest
	(*CreditDeductResponse)(nil),  // 6: grpc.CreditDeductResponse
	(*RefundCreditsRequest)(nil),  // 7: grpc.RefundCreditsRequest
	(*RefundCreditsResponse)(nil), // 8: grpc.RefundCreditsResponse
}
var file_pkg_grpc_credit_tracker_proto_depIdxs = []int32{
	3, // 0: grpc.CreditTracker.CheckCredits:input_type -> grpc.CreditCheckRequest
	5, // 1: grpc.CreditTracker.DeductCredits:input_type -> grpc.CreditDeductRequest
	7, // 2: grpc.CreditTracker.RefundCredits:input_type -> grpc.RefundCreditsRequest
	4, // 3: grpc.CreditTracker.CheckCredits:output_type -> grpc.CreditCheckResponse
	6, // 4: grpc.CreditTracker.DeductCredits:output_type -> grpc.CreditDeductResponse
	8, // 5: grpc.CreditTracker.RefundCredits:output_type -> grpc.RefundCreditsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_credit_tracker_proto_init() }
func file_pkg_grpc_credit_tracker_proto_init() {
	if File_pkg_grpc_credit_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_credit_tracker_proto_rawDesc), len(file_pkg_grpc_credit_tracker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_credit_tracker_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_credit_tracker_proto_depIdxs,
		EnumInfos:         file_pkg_grpc_credit_tracker_proto_enumTypes,
		MessageInfos:      file_pkg_grpc_credit_tracker_proto_msgTypes,
	}.Build()
	File_pkg_grpc_credit_tracker_proto = out.File
	file_pkg_grpc_credit_tracker_proto_goTypes = nil
	file_pkg_grpc_credit_tracker_proto_depIdxs = nil
}
