// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/credits/{licenseId}/assets/{assetId}/usage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed usage report for a specific license and asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credits"
                ],
                "summary": "Get License Asset Usage Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "License ID",
                        "name": "licenseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "assetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Date",
                        "name": "fromDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Date",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_credit-tracker_internal_creditrepo.LicenseAssetUsageReport"
                        }
                    }
                }
            }
        },
        "/v1/credits/{licenseId}/usage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get usage report for a license across all assets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credits"
                ],
                "summary": "Get License Usage Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "License ID",
                        "name": "licenseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Date",
                        "name": "fromDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Date",
                        "name": "toDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_credit-tracker_internal_creditrepo.LicenseUsageReport"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_DIMO-Network_credit-tracker_internal_creditrepo.LicenseAssetUsageReport": {
            "type": "object",
            "properties": {
                "assetDid": {
                    "description": "Asset DID",
                    "type": "string"
                },
                "currentCreditsRemaining": {
                    "description": "Number of credits remaining at the current time, this is not affected by the time period",
                    "type": "integer"
                },
                "fromDate": {
                    "description": "From date",
                    "type": "string"
                },
                "licenseId": {
                    "description": "License ID",
                    "type": "string"
                },
                "numOfCreditsGrantsPurchased": {
                    "description": "Number of credit grants purchased during the time period",
                    "type": "integer"
                },
                "numOfCreditsUsed": {
                    "description": "Number of credits used during the time period",
                    "type": "integer"
                },
                "toDate": {
                    "description": "To date",
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_credit-tracker_internal_creditrepo.LicenseUsageReport": {
            "type": "object",
            "properties": {
                "fromDate": {
                    "description": "From date",
                    "type": "string"
                },
                "licenseId": {
                    "description": "License ID",
                    "type": "string"
                },
                "numOfAssets": {
                    "description": "Number of assets accessed in a given time period",
                    "type": "integer"
                },
                "numOfCreditsGrantsPurchased": {
                    "description": "Number of credit grants purchased during the time period",
                    "type": "integer"
                },
                "numOfCreditsUsed": {
                    "description": "Number of credits used during the time period",
                    "type": "integer"
                },
                "toDate": {
                    "description": "To date",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DIMO Attestation API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
