name: gotest

on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - main

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run go mod verify
        run: go mod verify

      - name: Run Tests
        run: make test
